### ISSUE TITLE
Warning on Elixir v1.14

### ISSUE THREAD

**Issue by thbar** [rrrene/bunt#10]
I'm doing a bit of preliminary testing with https://github.com/elixir-lang/elixir/releases/tag/v1.14.0-rc.1, and noticed the following warning, so I'm opening an issue to report it :

```
==> bunt
Compiling 2 files (.ex)
warning: Application.get_env/3 is discouraged in the module body, use Application.compile_env/3 instead
  lib/bunt_ansi.ex:300: Bunt.ANSI

Generated bunt app
```

**Comment by rrrene** [comment]
Do you have any idea how to fix this?

I wrapped the code in question in a `Version.match/2` if-clause, but still get the exact same warning (for the code in the `else` block):

```elixir
  if Version.match?(System.version(), ">= 1.14.0-dev") do
    @color_aliases Application.compile_env(:bunt, :color_aliases, [])
  else
    @color_aliases Application.get_env(:bunt, :color_aliases, [])
  end
```

**Comment by thbar** [comment]
> Do you have any idea how to fix this?

Not yet ; I wonder if the simple presence of the code in the AST is enough to raise the warning, in which case there wouldn't be a solution.

I am concerned that Elixir 1.14 would be released without this solved, actually. Maybe it's worth raising the point on the Elixir forum or at the right place, if you know one such place?

**Comment by thbar** [comment]
I believe https://elixirforum.com/t/elixir-v1-14-0-rc-1-released/49581 is the right place, actually!

**Comment by LostKobrakai** [comment]
If you want to maintain compatibility for elixir `< 1.10` you can use a macro:

```elixir
defmodule Helper do
  defmacro compile_env(app, key, default) do
    if Version.match?(System.version(), ">= 1.10.0") do
      quote do
        Application.compile_env(unquote(app), unquote(key), unquote(default))
      end
    else
      quote do
        Application.get_env(unquote(app), unquote(key), unquote(default))
      end
    end
  end
end

defmodule A do
  require Helper
  @color_aliases Helper.compile_env(:elixir, :time_zone_database, [])
  # Only warns about the unused module attribute
end
```

**Comment by rrrene** [comment]
This was published in `v.0.2.1`. :+1:
