### ISSUE TITLE
Is this package compatible with windows ?

### ISSUE THREAD

**Issue by niahoo** [rrrene/bunt#2]
Hi, 

At work, we are currently on windows (7 & 10). This package outputs weird symbols and no colors.

Is it possible to make it work through a compatibility config ?

**Comment by rrrene** [comment]
I am pretty sure it is not compatible.

I would be open to a PR. But be sure to look at [IO.ANSI](http://elixir-lang.org/docs/stable/elixir/IO.ANSI.html) beforehand, since it has improved greatly since Bunt was introduced!

**Comment by niahoo** [comment]
Ok thank you :)
