### ISSUE TITLE
This doesn't work when building the escript.

### ISSUE THREAD

**Issue by nichochar** [rrrene/bunt#4]
I tried using this in a script compiled through `escript.build`, and the colors weren't printing out. I've had more troubles with the IO Device in general with the escript, something about it not running in the right shell... Anyway, just thought I'd let you know, you may want to close this as a won't fix.

**Comment by Trevoke** [comment]
I had the same problem building with distillery; I'm gonna need to switch to another package, I think.

**Comment by nichochar** [comment]
I have solved it by talking directly to bash, see [this stackoverflow question](http://stackoverflow.com/questions/42463316/why-does-io-columns-fail-when-running-through-the-escript)

**Comment by elibdev** [comment]
I had this same issue and came across a solution here:
https://elixirforum.com/t/unable-to-colorize-escript-text-output/2563

Adding the following line to my `config.exs` fixed this issue for me for this package and for the `IO.ANSI` package:

```elixir
config :elixir, ansi_enabled: true
```

Here's the relevant documentation:
https://hexdocs.pm/elixir/IO.ANSI.html#enabled?/0

**Comment by Trevoke** [comment]
That did the trick for me as well. Probably worth adding to the readme of this package.

**Comment by nichochar** [comment]
This indeed worked for me in my [project](https://github.com/nichochar/CLHN).

I will make a PR with the instructions
